### ISSUE TITLE
SGDQ 2021 Silly Block length

### ISSUE THREAD

**Issue by Superjustinbros** [gman003/gdqrs#1]
Currently, according to the review page, the end of Summer Games Done Quick 2021's Silly Block was Racing Pitch. From what I remember, the actual end of the Silly Block was ALTF4, but I don't remember any evidence besides the silly tones of the marathon taking a noticeable dip by the Time Gate: Knight's Chase run.

**Comment by gman003** [comment]
Defining the edges of some of those blocks is kind of subjective, especially for Silly Block and Awful Block. Official documentation doesn't list what games are in what blocks, or even acknowledge blocks existing, so I often have to make my own judgement call.

My thinking for ending it after Racing Pitch was that the two runs after it, Need For Speed and Evolution Skateboarding, didn't seem like particularly silly games, certainly not at the level of Fight Crab or Racing Pitch. But you're right, Wheels and ALTF4 probably fit into it, and even Time Gate is more of a "laugh as we play this absurd game" run than a "watch as we perfectly execute this hard game" run.

I decided to see if the host ever said anything describing the block, and shortly after the ALTF4 run, cartridgeblowers described Time Gate: Knight's Chase as "the end of our Silly Block", which I'm going to consider authoritative.

Thanks for pointing this out!
