### ISSUE TITLE
AGDQ 2023 Castlevania Block

### ISSUE THREAD

**Issue by Superjustinbros** [gman003/gdqrs#3]
The Castlevania: Harmony of Despair and Castlevania: Aria of Sorrow runs do not have the brown coloring of the Castlevania blocks from other marathons.

**Comment by gman003** [comment]
Fixed in the latest update. Think it slipped through because one of the runs was an incentive, not on the original schedule - I don't normally label two runs as a "block". But three seems worth noting, especially when it's a block that's been bigger in other marathons.
