### ISSUE TITLE
SGDQ 2019 - Looney Tunes & Rhino Rumble Couch Incomplete

### ISSUE THREAD

**Issue by CardsOfTheHeart** [gman003/gdqrs#4]
'Sup, dood!

The couch info for the SGDQ 2019 runs of Looney Tunes and Rhino Rumble is incomplete. As the world record holder for Rhino Rumble, I was on the couch for both games, but my name is not listed.

I could not find another place to report this. Appreciate the concept, dood!

**Comment by gman003** [comment]
Good spot! I'd copied the couch listings from the GDQ Youtube uploads, which seems to be where the mistakes originated. Appears they left you off both, and incorrectly copied that listing to Rhino Rumble despite having far fewer people on-camera. I'll go back and fix that, and make sure to tag you as the WRH.

**Comment by gman003** [comment]
Fixed as of c97f2f28fe12661120333b8f78886f5ed61675e1
